branches:
  only:
  - master
language: python
python:
  - 3.6
sudo: required
services:
  - docker
install:
  - pip install ghp-import
  - git clone https://github.com/getpelican/pelican-plugins
script:
  - make publish
notifications:
  email:
    on_success: always
    on_failure: always
env:
  global:
    secure: UKv0Ae4OnqTZTVFCaIh9S1NPbm1+9Q+ptiw7cAWxhGzWcOpgk5I7wqmPE6jdWuwJXTgE8NftZ7mFvN07N75qwxQ9Fl2DU1OcMddzHxOoeAnSdBmhc5yYXPG+7wDcl8N/F54EXw5LAgBROfv9lREs7taUEfexwDAIsumq6o+Y14PJuZ4MsOygy4DAqnDrj6pjuNJ1juBGM1E+WAYyvAqdLavBiVkBpfwkVYw1LIfO04daVYNzMRjGytLigom2yKWeIWOOrYye3ydZ043VCM2cfU20eJXXHGQpcrdWL/X42C2y/gSnyxSJAr+Mjys9CYL5YhbXuwtJpab5tEZeHJiMeXE8tup/Vz5/XavXer+BC6i38IYJuzDpgZiY698Nbao/YLusG8rgGYkj6wa6D1QX86xuzejrMQUD7FOlM7GOJJpHG2DG3aYMJdoPbdQw9D5EhSSWPUgBUFD1wd0Ql/RqHUyQhob8KCj9IoLK0I9UgOmKVZ9Ypvyot6B8haTxR3N7xPk56P0F2KQFPYrWiFRkGoPy63Auh762fexnhle1xUrpgvAIMKBMazq/Dk4w2ZO1o7NzcYxs+oJ63g7qqyJMvBJB0USJGU84jqWuZtDAHcRjJ3QVOcgior7+3D9z8jlIS4Hz7v/QxS6V7dPiPfXiK16bwJkIZfYDV5yQbSCBbCY=
before_install:
  - git submodule update --init --recursive
after_success: make github
